### ISSUE TITLE
RuntimeError: OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by dcflachs** [msiemens/tinydb-smartcache#5]
I am getting the following error when trying to use tinydb-smartcache with Tinydb v3.15.0  

File "/home/jovyan/work/python/tiny_smartcache.py", line 114, in insert
    for query in self._query_cache:
RuntimeError: OrderedDict mutated during iteration

**Comment by dcflachs** [comment]
@msiemens So I have found a modification that fixes the above issue. For each instance of the line `for query in self._query_cache:` I substituted the line `for query in [i for i in self._query_cache]:`. I am still very new to the python language so I not really certain if this is an efficient solution or just an ugly hack. What do you think?

**Comment by msiemens** [comment]
Thanks for reporting this, @dcflachs! Seems like there was a change in msiemens/tinydb#231 which accidentally broke this extension. The issue has been fixed now and I've just released tinydb-smartcache v1.0.3 which includes the fix 🙂
